---
name: orangetheses
services:
  orangetheses_test_solr:
    type: solr:8.4
    portforward: true
    core: orangetheses-core-test
    config:
      dir: "solr/conf"
  orangetheses_development_solr:
    type: solr:8.4
    portforward: true
    core: orangetheses-core-development
    config:
      dir: "solr/conf"
proxy:
  orangetheses_test_solr:
    - orangetheses.test.solr.lndo.site:8983
  orangetheses_development_solr:
    - orangetheses.dev.solr.lndo.site:8983
