---
development:
  url: <%= ENV['SOLR_URL'] || "http://#{ENV["lando_orangetheses_development_solr_conn_host"] || "127.0.0.1"}:#{ENV["lando_orangetheses_development_solr_conn_port"] || 8983}/solr/orangetheses-core-development" %>
test: &test
  url: <%= ENV['SOLR_URL'] || "http://#{ENV["lando_orangetheses_test_solr_conn_host"] || "127.0.0.1"}:#{ENV['SOLR_TEST_PORT'] || ENV["lando_orangetheses_test_solr_conn_port"] || 8888}/solr/orangetheses-core-test" %>
production:
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/catalog-production" %>
